import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";
//import { twMerge } from "tailwindcss";

const inter = Inter({ subsets: ["latin"]});

export const metadata: Metadata = {
  title: {
    template: "Athena",
    default: "Athena AI"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={(inter.className, "antialiased bg-[#EAEEFE]")}>
        {children}
      </body>
    </html>
  );
}
